### ISSUE TITLE
Other hints, e.g. "no-inline"?

### ISSUE THREAD

**Issue by kripken** [WebAssembly/branch-hinting#18]
In the wasm GC space we have multiple requests for a "no-inline" annotation. It could be used in both tools and VMs, so much like branch hinting it makes sense to consider standardizing it, I think. So I though to open an issue here to discuss thoughts on how to do that.

One option might be separate proposals for each, "branch hinting", "no-inline", etc. Another option might be a single "code hints" proposal.

I don't feel strongly either way. The main difference might be procedural: separate small proposals is more modular, but also more work, especially when each such proposal seems like it would be quite small. And the proposals would be quite similar, all using parallel custom sections etc.

Thoughts?

If it's helpful, some concrete details about "no-inline"/"inline": There are cases in Java where we know a function is definitely hot and worth inlining, or definitely cold and not worth inlining. For example a class initialization check will do a simple condition "has been initialized" and the first time it is reached it will call the actual initialization code. The check is hot, but the init code is very cold. As a result, we'd like both optimizers like Binaryen to inline or not inline based on that information, and VMs that do runtime inlining can use it as well (which would have less overhead than collecting runtime profile data in order to make the decision on whether to inline).

**Comment by titzer** [comment]
I generally support the concept of inline/no-inline. I also think it would be useful to think of it in terms of a more general code hints section, rather than doing one-offs. One rationale for that is that the optimizing tier of an engine will likely want to load all the hints for a function together from one section, rather than going through multiple sections (i.e. spatial locality).

**Comment by yuri91** [comment]
This inline/no-inline hint would be applied to the `call` instruction, right?

Then I can see it using the same format as branch hinting.

About using the same custom section vs a different one, I can see reasons for both:

different sections: 
- an engine/tool can just look at what it's interested in.
- easier to extend in a backward-compatible way

same section: 
- more compact and possibly more efficient to parse
- if multiple small features are packed in one section, tools will be more incentivised to recognise/preserve it as a whole 

Assuming that we want to go for a single section, what changes would be needed?

The name could become `metadata.code.hint`, and we could add more "opcodes" on top of "0" (branch-unlikely) and "1" (branch-likely), like "2" (inline-call), "3" (no-inline-call)

**Comment by kripken** [comment]
> This inline/no-inline hint would be applied to the call instruction, right?

Good question. I think it would be enough to put it on the called functions for the Java use case I currently have in mind, and for a few other use cases I'm aware of. I can imagine use cases for the call instruction as well, but I'm not sure how realistic they are. Actually now that we mention it, I think this came up in a CG discussion as a comment? But I don't remember what conclusions we came to then, if any.

And good points about the tradeoffs with single vs multiple sections. Neither seems obviously better, though I lean slightly towards a single section.

**Comment by yuri91** [comment]
Ah I see. We can still use the same format to hint the function itself instead of an instruction, by using the offset `0`.

**Comment by osa1** [comment]
It would be great to have this.

We have a concrete example in https://github.com/dart-lang/sdk/issues/54395 where we have an error handling code path that we want to never inline. If wasm-opt inlines it in compile time, or V8 inlines it in runtime (or instantiation time), V8 decides to *not* speculatively inline the calls to the parent function (because the function gets large with the error handling), leaving 7% perf on the table.

Re: "always inline" and "never inline", I think "never inline" is more important, as inlining can in principle be done by the initial code generator, but it's currently not possible to prevent inlining of a function by the follow-up passes and engines. Even if we generate `call_indirect` or `call_ref` to prevent inlining, wasm-opt can turn those into direct calls and V8 can do speculative inlining.

(I currently don't have a use case for "always inline".)

Re: annotating the `call` instructions vs. functions, I think ideally we want both, for the same reason as above. wasm-opt can reveal more inlining opportunities and create `call` instructions. In those cases it can look at the hint for the function being directly called. In addition, hints on functions can influence speculative inlining as well (e.g. a never-inline function should never be speculatively inlined).

**Comment by yuri91** [comment]
@osa1 there is now a "Compilation Hints" proposal: https://github.com/WebAssembly/compilation-hints/blob/main/proposals/compilation-hints/Overview.md

It does not currently include an inlining hint, but it was mentioned as possibly in scope.

**Comment by yuri91** [comment]
Closing the issue, as the compilation hints proposal is taking care of this: https://github.com/WebAssembly/compilation-hints/pull/5
