### ISSUE TITLE
Simpler alternative annotations?

### ISSUE THREAD

**Issue by tlively** [WebAssembly/branch-hinting#29]
Would it be possible to simplify the branch hint annotation syntax? As a modest simplification, the annotations could use `0` and `1` instead of `"\00"` and `"\01"`. It would also be nice to add `(@likely)` and `(@unlikely)` annotations, potentially as aliases of the longer annotations.

Besides the spec interpreter, what tools currently consume the branch hinting annotations?

**Comment by yuri91** [comment]
The idea is that the `@metadata.code.<name> "..."` syntax works universally for any code metadata section.
This is important because `@custom` cannot be used to round trip such sections.

It's totally possible to add specialized annotations for specific metadata formats. For branch hinting, I would favor something like `(@likely)/(@unlikely)` over just using numbers instead of the strings for 0 and 1.

But I deliberately kept this out of the proposal because I don't think that there is much practical use for manually annotating wat files, other than roundtripping tests and debugging purposes.

For instance, the wabt tools can consume and round trip code metadata sections, but not branch hinting specifically, and I personally found it sufficient for debugging modules produced by Cheerp.

It helps that in the case of branch hinting the binary format is trivial, and interpreting the "\00" and "\01" is easy. A more complex format probably warrants a specialized syntax from day 1.

**Comment by tlively** [comment]
Thanks, that makes sense!
